### ISSUE TITLE
Update to 1.20.1 Please

### ISSUE THREAD

**Issue by sternschnaube** [mineblock11/Illagers-Wear-Armor-For-Fabric#3]
It's marked for 1.20.1 on Modrinth, but it doesn't work.

![image](https://github.com/mineblock11/Illagers-Wear-Armor-For-Fabric/assets/120551916/550bf5ea-0aff-4331-9c53-e28d3e838cbc)

**Comment by mineblock11** [comment]
Whoops, I'll push a hotfix tonight

**Comment by sternschnaube** [comment]
Thanks 😊
